apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3je4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-3je4@sha256:0f4c70ad896768d554bd56621405b8ca68cf03a5790e167c0b33a89b26d07973
        name: my-nodejs
        resources: {}
status: {}
